/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: d1198467ebe05cb4b415b62699c86496)
/// <reference types="@cloudflare/workers-types" />

interface __BaseEnv_Env {
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/workers-ai");
		durableNamespaces: "UserAccount" | "WorkersAiEmbeddingsGatekeeper" | "WorkersAiImageGenerationGatekeeper" | "WorkersAiSpeechRecognitionGatekeeper" | "WorkersAiTextToSpeechGatekeeper" | "WorkersAiClassificationGatekeeper";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
declare module "*.txt" {
	const value: string;
	export default value;
}
